timber_crops/crops_optimizer/urls.py
from django.urls import path
from .views import (views, views_resource, views_nat_struct,
                    views_resource_cat, views_need_cat, views_nat_struct_cat)

urlpatterns = [
    path('', views.home, name='home'),
    path('hello/', views.hello, name='hello'),
    path('settings-hub/', views.settings_hub, name='settings_hub'),
    path('delete-game-mode/', views.delete_game_mode, name='delete_game_mode'),
    path('modify-game-mode/<int:game_mode_id>/', views.modify_game_mode, name='modify_game_mode'),
    path('need-category/', views_need_cat.NeedCatListView.as_view(), name='need_cat_list'),
    path('need-category/create/', views_need_cat.NeedCatCreateView.as_view(), name='need_cat_create'),
    path('need-category/<int:pk>/update/', views_need_cat.NeedCatUpdateView.as_view(), name='need_cat_update'),
    path('need-category/<int:pk>/delete/', views_need_cat.NeedCatDeleteView.as_view(), name='need_cat_delete'),
    path('resource-category/', views_resource_cat.ResourceCatListView.as_view(), name='resource_cat_list'),
    path('resource-category/create/', views_resource_cat.ResourceCatCreateView.as_view(), name='resource_cat_create'),
    path('resource-category/<int:pk>/update/', views_resource_cat.ResourceCatUpdateView.as_view(), name='resource_cat_update'),
    path('resource-category/<int:pk>/delete/', views_resource_cat.ResourceCatDeleteView.as_view(), name='resource_cat_delete'),
    path('natural-structure-category/', views_nat_struct_cat.NatStructCatListView.as_view(), name='nat_struct_cat_list'),
    path('natural-structure-category/create/', views_nat_struct_cat.NatStructCatCreateView.as_view(), name='nat_struct_cat_create'),
    path('natural-structure-category/<int:pk>/update/', views_nat_struct_cat.NatStructCatUpdateView.as_view(), name='nat_struct_cat_update'),
    path('natural-structure-category/<int:pk>/delete/', views_nat_struct_cat.NatStructCatDeleteView.as_view(), name='nat_struct_cat_delete'),
    path('resource/', views_resource.ResourceListView.as_view(), name='resource_list'),
    path('resource/create/', views_resource.ResourceCreateView.as_view(), name='resource_create'),
    path('resource/<int:pk>/update/', views_resource.ResourceUpdateView.as_view(), name='resource_update'),
    path('resource/<int:pk>/delete/', views_resource.ResourceDeleteView.as_view(), name='resource_delete'),
    path('natural-structure/', views_nat_struct.NatStructListView.as_view(), name='nat_struct_list'),
    path('natural-structure/create/', views_nat_struct.NatStructCreateView.as_view(), name='nat_struct_create'),
    path('natural-structure/<int:pk>/update/', views_nat_struct.NatStructUpdateView.as_view(), name='nat_struct_update'),
    path('natural-structure/<int:pk>/delete/', views_nat_struct.NatStructDeleteView.as_view(), name='nat_struct_delete'),
]

timber_crops/timber_crops/urls.py
from django.contrib import admin
from django.urls import path
# from django.urls import path
# from . import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('crops_optimizer/', include('crops_optimizer.urls')),
    path('', include('crops_optimizer.urls')),
]

timber_crops/crops_optimizer/models.py
from django.db import models

# Create your models here.

class GameMode(models.Model):
    name = models.CharField(max_length=100, unique=True)
    food_consumption_percentage = models.PositiveIntegerField()
    food_consumption_daily_unit = models.DecimalField(max_digits=5, decimal_places=2)
    locked = models.BooleanField(default=False)  

    def __str__(self):
        return self.name

class NeedCat(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Need(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(NeedCat, on_delete=models.PROTECT, related_name='needs')

    def __str__(self):
        return self.name
    
class ResourceCat(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Resource(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(ResourceCat, on_delete=models.PROTECT, related_name='resources')

    def __str__(self):
        return self.name
    
class NatStructCat(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class NatStruct(models.Model):
    name = models.CharField(max_length=100)
    days_to_grow = models.PositiveIntegerField()
    days_between_harvest = models.PositiveIntegerField(null=True)
    resource_cut_yield = models.PositiveIntegerField(null=True)
    resource_harvest_yield = models.PositiveIntegerField(null=True)
    category = models.ForeignKey(NatStructCat, on_delete=models.PROTECT, related_name='nat_structs')
    resource_cut = models.ForeignKey(Resource, on_delete=models.PROTECT, related_name='cut_nat_structs', null=True)
    resource_harvest = models.ForeignKey(Resource, on_delete=models.PROTECT, related_name='harvest_nat_structs', null=True)

    def __str__(self):
        return self.name

timber_crops/crops_optimizer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import GameModeForm, ModifyGameModeForm#, ModifyLockForm
from .models import GameMode
import logging
from django.contrib import messages
from django.http import HttpRequest
# Create your views here.


from django.http import HttpResponse

def hello(request):
    return HttpResponse("Hello, TimberCrops!")

def home(request):
    if request.method == 'POST':
        number_of_beavers = int(request.POST.get('number_of_beavers'))
        carrots_selected = 'carrots' in request.POST
        carrots_food_ratio = int(request.POST.get('carrots_food_ratio'))
        bread_selected = 'bread' in request.POST
        bread_food_ratio = int(request.POST.get('bread_food_ratio'))

        daily_food_intake = 2.5
        number_daily_food = daily_food_intake * number_of_beavers

        foods = {
            "carrots" : {
                "selected" : carrots_selected,
                "ratio_to_food" : carrots_food_ratio,
                "crop_yield" : 3,
                "days_between_harvest" : 4,
                "transformation_multiplier" : 1
            },
            "bread" : {
                "selected" : bread_selected,
                "ratio_to_food" : bread_food_ratio,
                "crop_yield" : 3,
                "days_between_harvest" : 10,
                "transformation_multiplier" : 5
            }
        }

        sum_food_ratio = sum(food_data["ratio_to_food"] for food_data in foods.values())

        for food_name, food_data in foods.items():
            if food_data["selected"]:
                ratio_to_food = food_data["ratio_to_food"]
                crop_yield = food_data["crop_yield"]
                days_between_harvest = food_data["days_between_harvest"]
                transformation_multiplier = food_data["transformation_multiplier"]

                required_daily_food_prod = ratio_to_food * number_daily_food / sum(food["ratio_to_food"] for food in foods.values())
                daily_crop_prod = crop_yield / days_between_harvest * transformation_multiplier
                required_crops_number = required_daily_food_prod / daily_crop_prod

                food_data["required_crops_number"] = required_crops_number
            else:
                food_data["required_crops_number"] = 0

        context = {
            'number_of_beavers': number_of_beavers,
            'carrots_selected': carrots_selected,
            'bread_selected': bread_selected,
            'required_carrot_crops': foods["carrots"]["required_crops_number"],
            'required_wheat_crops': foods["bread"]["required_crops_number"],
            # Add other variables here
            }    


        return render(request, 'home.html', context)

    return render(request, 'home.html')


def settings_hub(request: HttpRequest) -> HttpResponse: #type hinting used to specify the expected type of the request
    form = GameModeForm()
    
    if request.method == 'POST':
        form = GameModeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('settings_hub')

    existing_game_modes = GameMode.objects.all()

    context = {'form': form, 'existing_game_modes': existing_game_modes}
    return render(request, 'settings_hub.html', context)

def modify_game_mode(request, game_mode_id):
    game_mode = get_object_or_404(GameMode, id=game_mode_id)
    
    if request.method == 'POST':
        form = ModifyGameModeForm(request.POST, instance=game_mode)
        if form.is_valid():
            form.save()
            return redirect('settings_hub')
    else:
        form = ModifyGameModeForm(instance=game_mode)

    return render(request, 'modify_game_mode.html', {'form': form, 'game_mode': game_mode})






def delete_game_mode(request):
    if request.method == 'POST':
        game_mode_id = request.POST.get('game_mode_id')
        # request
        if game_mode_id:
            GameMode.objects.filter(id=game_mode_id).delete()
    return redirect('settings_hub')  # Redirect back to the settings hub

timber_crops/crops_optimizer/views/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ..forms import GameModeForm, ModifyGameModeForm#, SimulationForm
from ..models import GameMode
import logging
from django.contrib import messages
from django.http import HttpRequest
from decimal import Decimal
# Create your views here.


from django.http import HttpResponse

def hello(request):
    return HttpResponse("Hello, TimberCrops!")

def home(request):
    game_modes = GameMode.objects.all()
    context = {
        'game_modes': game_modes,
    }
    if request.method == 'POST':
        number_of_beavers = int(request.POST.get('number_of_beavers'))
        carrots_selected = 'carrots' in request.POST
        carrots_food_ratio = int(request.POST.get('carrots_food_ratio'))
        bread_selected = 'bread' in request.POST
        bread_food_ratio = int(request.POST.get('bread_food_ratio'))

        selected_game_mode_id = int(request.POST.get('game_mode'))
        try:
            selected_game_mode = GameMode.objects.get(pk=selected_game_mode_id)
        except GameMode.DoesNotExist:
            # Manage here the case where the GameMode does not exist
            pass
        else:
            daily_food_intake = selected_game_mode.food_consumption_daily_unit
            #previously daily_food_intake = 2.5
        number_daily_food = daily_food_intake * number_of_beavers

        foods = {
            "carrots" : {
                "selected" : carrots_selected,
                "ratio_to_food" : carrots_food_ratio,
                "crop_yield" : 3,
                "days_between_harvest" : 4,
                "transformation_multiplier" : 1
            },
            "bread" : {
                "selected" : bread_selected,
                "ratio_to_food" : bread_food_ratio,
                "crop_yield" : 3,
                "days_between_harvest" : 10,
                "transformation_multiplier" : 5
            }
        }

        sum_food_ratio = sum(
        food_data["ratio_to_food"]
        for food_data in foods.values()
        if food_data["selected"]
        )

        for food_name, food_data in foods.items():
            if food_data["selected"]:
                ratio_to_food = food_data["ratio_to_food"]
                crop_yield = food_data["crop_yield"]
                days_between_harvest = food_data["days_between_harvest"]
                transformation_multiplier = food_data["transformation_multiplier"]
                
                required_daily_food_prod = ratio_to_food * number_daily_food / sum_food_ratio #sum(food["ratio_to_food"] for food in foods.values())
                daily_crop_prod = crop_yield / days_between_harvest * transformation_multiplier
                # print("Value of sum_food_ratio:", sum_food_ratio)
                # print("Value of ratio_to_food:", ratio_to_food)
                # print("Value of daily_crop_prod:", daily_crop_prod)
                required_crops_number = Decimal(required_daily_food_prod) / Decimal(daily_crop_prod)
                # print("Value of required_crops_number:", required_crops_number)
                food_data["required_crops_number"] = required_crops_number
            else:
                food_data["required_crops_number"] = 0

        result_context = {
            'selected_game_mode_id': selected_game_mode_id,
            'number_of_beavers': number_of_beavers,
            'carrots_selected': carrots_selected,
            'bread_selected': bread_selected,
            'required_carrot_crops': foods["carrots"]["required_crops_number"],
            'required_wheat_crops': foods["bread"]["required_crops_number"],
            # Add other variables here
            }    

       
        context = {**context, **result_context}
        
        print("Value of context: ", context)
        # return render(request, 'home.html', context)
    
    return render(request, 'home.html', context)
                  #{'game_modes': game_modes})


def settings_hub(request: HttpRequest) -> HttpResponse: #type hinting used to specify the expected type of the request
    form = GameModeForm()
    
    if request.method == 'POST':
        form = GameModeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('settings_hub')

    existing_game_modes = GameMode.objects.all()

    context = {'form': form, 'existing_game_modes': existing_game_modes}
    return render(request, 'settings_hub.html', context)

def modify_game_mode(request, game_mode_id):
    game_mode = get_object_or_404(GameMode, id=game_mode_id)
    
    if request.method == 'POST':
        form = ModifyGameModeForm(request.POST, instance=game_mode)
        if form.is_valid():
            form.save()
            return redirect('settings_hub')
    else:
        form = ModifyGameModeForm(instance=game_mode)

    return render(request, 'modify_game_mode.html', {'form': form, 'game_mode': game_mode})






def delete_game_mode(request):
    if request.method == 'POST':
        game_mode_id = request.POST.get('game_mode_id')
        # request
        if game_mode_id:
            GameMode.objects.filter(id=game_mode_id).delete()
    return redirect('settings_hub')  # Redirect back to the settings hub

timber_crops/crops_optimizer/views/views_nat_struct.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from ..models import NatStruct
from ..forms import NatStructForm

class NatStructListView(ListView):
    model = NatStruct
    template_name = 'nat_struct_list.html'
    context_object_name = 'nat_structs'

class NatStructCreateView(CreateView):
    model = NatStruct
    form_class = NatStructForm
    template_name = 'nat_struct_form.html'
    success_url = reverse_lazy('nat_struct_list')

class NatStructUpdateView(UpdateView):
    model = NatStruct
    form_class = NatStructForm
    template_name = 'nat_struct_form.html'
    success_url = reverse_lazy('nat_struct_list')

class NatStructDeleteView(DeleteView):
    model = NatStruct
    success_url = reverse_lazy('nat_struct_list')

timber_crops/crops_optimizer/views/views_nat_struct_cat.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from ..models import NatStructCat
from ..forms import NatStructCatForm

class NatStructCatListView(ListView):
    model = NatStructCat
    template_name = 'nat_struct_cat_list.html'
    context_object_name = 'nat_struct_categories'

class NatStructCatCreateView(CreateView):
    model = NatStructCat
    form_class = NatStructCatForm
    template_name = 'nat_struct_cat_form.html'
    success_url = reverse_lazy('nat_struct_cat_list')

class NatStructCatUpdateView(UpdateView):
    model = NatStructCat
    form_class = NatStructCatForm
    # fields = ['name']
    template_name = 'nat_struct_cat_form.html'
    success_url = reverse_lazy('nat_struct_cat_list')

class NatStructCatDeleteView(DeleteView):
    model = NatStructCat
    success_url = reverse_lazy('nat_struct_cat_list')

timber_crops/crops_optimizer/views/views_need_cat.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from ..models import NeedCat
from ..forms import NeedCatForm

class NeedCatListView(ListView):
    model = NeedCat
    template_name = 'need_cat_list.html'
    context_object_name = 'need_cat'

class NeedCatCreateView(CreateView):
    model = NeedCat
    form_class = NeedCatForm
    # fields = ['name']
    template_name = 'need_cat_form.html'
    success_url = reverse_lazy('need_cat_list')

class NeedCatUpdateView(UpdateView):
    model = NeedCat
    form_class = NeedCatForm
    # fields = ['name']
    template_name = 'need_cat_form.html'
    success_url = reverse_lazy('need_cat_list')

class NeedCatDeleteView(DeleteView):
    model = NeedCat
    success_url = reverse_lazy('need_cat_list')

timber_crops/crops_optimizer/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
<head>
    <!-- Add your common meta tags, styles, etc. here -->
    <title>{% block title %}Default Title{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'crops_optimizer/styles.css' %}">
</head>
<body>
    <header>
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'settings_hub' %}" style="margin-left: 50px;">Settings Hub</a>
        <!-- Other navigation links or content can be added here -->
        <div class="dropdown">
            <button class="dropbtn">Static Tables</button>
            <div class="dropdown-content">
                <a href="{% url 'need_cat_list' %}">Need Categories</a>
                <a href="{% url 'resource_cat_list' %}">Resource Categories</a>
                <a href="{% url 'nat_struct_cat_list' %}">Natural Structure Categories</a>
                <a href="{% url 'resource_list' %}">Resources</a>
                <a href="{% url 'nat_struct_list' %}">Natural Structures</a>
                <!-- Add links to other static data tables here -->
            </div>
        </div>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>

    {% block script %}{% endblock %}
</body>
</html>

timber_crops/crops_optimizer/templates/home.html
{% extends 'base.html' %} {% block title %}Welcome to TimberCrops{% endblock %}
{% block content %}

<h1>Welcome to TimberCrops</h1>
<p>This is your crop optimization tool for the Timberborn game.</p>

<br />

<!-- home.html -->
<form method="post">
  {% csrf_token %}
  <table class="styled-table" style="width: 400px">
    <tr>
      <th>Game Mode:</th>
      <td>
        <select id="game_mode" name="game_mode" required>
          <option value="" 
            {% if selected_game_mode_id %}disabled{% endif %} 
            {% if not selected_game_mode_id %}selected{% endif %}>Select a Game Mode
          </option>
          {% for mode in game_modes %}
            <option value="{{ mode.id }}" {% if mode.id == selected_game_mode_id %}selected{% endif %}>{{ mode.name }}</option>
          {% endfor %}
        </select>
      </td>
    </tr>
    <tr>
      <th>Number of Beavers:</th>
      <td>
        <input type="number" id="number_of_beavers" name="number_of_beavers" required value="{{ number_of_beavers }}"/>
      </td>
    </tr>
    <tr>
      <th></th>
      <th></th>
      <th>Proportion of foods</th>
    </tr>
    <tr>
      <th>Carrots:</th>
      <td><input type="checkbox" id="carrots" name="carrots" {% if carrots_selected %}checked{% endif %} /></td>
      <td>
        <input type="number" id="carrots_food_ratio" name="carrots_food_ratio" required 
        value="1"/>
      </td>
    </tr>
    <tr>
      <th>Bread:</th>
      <td><input type="checkbox" id="bread" name="bread" {% if bread_selected %}checked{% endif %} /></td>
      <td>
        <input type="number" id="bread_food_ratio" name="bread_food_ratio" required 
        value="1"/>
      </td>
    </tr>
  </table>
  <br />
  <button type="submit">Start Simulation</button>
</form>

{% if submitted %}
<h2>Results</h2>
{% endif %}

{% if required_carrot_crops is not None or required_wheat_crops is not None %}
<table class="styled-table" style="width:400px">
    {% if required_carrot_crops is not None %}
    <tr>
        <th>Number of carrot crops required:</th>
        <td>{{ required_carrot_crops }}</td>
    </tr>
    {% endif %} 
    {% if required_wheat_crops is not None %}
    <tr>
        <th>Number of wheat crops required:</th>
        <td>{{ required_wheat_crops }}</td>
    </tr>
    {% endif %}
</table>
{% endif %}


{% endblock %}

timber_crops/crops_optimizer/templates/modify_game_mode.html
{% extends 'base.html' %}
{% comment %} {% load static %} {% endcomment %}

{% block title %}Settings Hub{% endblock %}

{% block content %}
<h2>Modify Game Mode: {{ game_mode.name }}</h2>
    <table class="styled-table">
        <tr>
            <th>Name</th>
            <th>Food Consumption (%)</th>
            <th>Food Consumption (daily unit)</th>
            <th>Locked</th>
        </tr>
        <tr>
            <td>{{ game_mode.name }}</td>
            <td>{{ game_mode.food_consumption_percentage }} %</td>
            <td>{{ game_mode.food_consumption_daily_unit }}</td>
            <td>{{ game_mode.locked }}</td>
        </tr>
    </table>

    <br>
    <form method="post">
        {% csrf_token %}
        <table class="styled-table" style="width:500px">
            <tr>
                <th>Name</th>
                <td>{{ form.name.errors }} {{ form.name }}</td>
            </tr>
            <tr>
                <th>Food Consumption (%)</th>
                <td>{{ form.food_consumption_percentage.errors }} {{ form.food_consumption_percentage }}</td>
            </tr>
            <tr>
                <th>Food Consumption (daily unit)</th>
                <td>{{ form.food_consumption_daily_unit.errors }} {{ form.food_consumption_daily_unit }}</td>
            </tr>
            <tr>
                <th>{{form.locked.label_tag}}</th>
                <td>{{ form.locked.errors }} {{ form.locked }}</td>
            </tr>
        </table>
        <button type="submit">Save Changes</button>
    </form>
    <br>

{% endblock %}

{% block script %}
<script>
    // Get existing data from the page
    var existingName = "{{ game_mode.name }}";
    var existingPercentage = "{{ game_mode.food_consumption_percentage }}";
    var existingDailyUnit = "{{ game_mode.food_consumption_daily_unit }}";
    
    // Fill up the form fields
    document.addEventListener("DOMContentLoaded", function() {
        document.querySelector("#id_name").value = existingName;
        document.querySelector("#id_food_consumption_percentage").value = existingPercentage;
        document.querySelector("#id_food_consumption_daily_unit").value = existingDailyUnit;
    });
</script>
{% endblock %}
    
    

    

timber_crops/crops_optimizer/templates/nat_struct_cat_form.html
{% extends "base.html" %}

{% block content %}
<h1>{% if 'create' in request.path %}Create
    {% else %}Update{% endif %} 
    Natural Structure Category</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
        {% if 'create' in request.path %}Create
        {% else %}Update{% endif %}</button>
</form>
<br><br>
<a href="{% url 'nat_struct_cat_list' %}">Back to List</a>
{% endblock %}

timber_crops/crops_optimizer/templates/nat_struct_cat_list.html
{% extends "base.html" %}

{% block content %}
<h1>Natural Structure Categories</h1>
<a href="{% url 'nat_struct_cat_create' %}" class="btn btn-primary">Create New</a>
<br><br>
<table class="styled-table" style="width: 400px">
    <thead>
        <tr>
            <th>Actions</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        {% for category in nat_struct_categories %}
            <tr>
                <td style="display: flex; justify-content: space-around;">
                    <a href="{% url 'nat_struct_cat_update' category.pk %}" class="btn update-button">Update</a>
                    <form method="post" action="{% url 'nat_struct_cat_delete' category.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn delete-button">Delete</button>
                    </form>
                </td>
                <td>{{ category.name }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

timber_crops/crops_optimizer/templates/nat_struct_form.html
{% extends "base.html" %}

{% block content %}
<h1>{% if 'create' in request.path %}Create
    {% else %}Update{% endif %} 
    Natural Structure</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
        {% if 'create' in request.path %}Create
        {% else %}Update{% endif %}</button>
</form>
<br><br>
<a href="{% url 'nat_struct_list' %}">Back to List</a>
{% endblock %}

timber_crops/crops_optimizer/templates/nat_struct_list.html
{% extends "base.html" %}

{% block content %}
<h1>Natural Structures</h1>
<a href="{% url 'nat_struct_create' %}" class="btn btn-primary">Create New</a>
<br><br>
<table class="styled-table" style="width: 400px">
    <thead>
        <tr>
            <th>Actions</th>
            <th>Name</th>
            <th>Resource category</th>
            <th>Days to grow</th>
            <th>Cut Resource</th>
            <th>Cut Resource yield</th>
            <th>Harvested Resource</th>
            <th>Days between harvest</th>
            <th>Harvested Resource yield</th>
        </tr>
    </thead>
    <tbody>
        {% for nat_struct in nat_structs %}
            <tr>
                <td style="display: flex; justify-content: space-around;">
                    <a href="{% url 'nat_struct_update' nat_struct.pk %}" class="btn update-button">Update</a>
                    <form method="post" action="{% url 'nat_struct_delete' nat_struct.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn delete-button">Delete</button>
                    </form>
                </td>
                <td>{{ nat_struct.name }}</td>
                <td>{{ nat_struct.category }}</td>
                <td>{{ nat_struct.days_to_grow }}</td>
                <td>{{ nat_struct.resource_cut }}</td>
                <td>{{ nat_struct.resource_cut_yield }}</td>
                <td>{{ nat_struct.resource_harvest }}</td>
                <td>{{ nat_struct.days_between_harvest }}</td>
                <td>{{ nat_struct.resource_harvest_yield }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

timber_crops/crops_optimizer/templates/need_cat_form.html
{% extends "base.html" %}

{% block content %}
<h1>{% if 'create' in request.path %}Create
    {% else %}Update{% endif %} 
    Need Category</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
        {% if 'create' in request.path %}Create
        {% else %}Update{% endif %}</button>
</form>
<br><br>
<a href="{% url 'need_cat_list' %}">Back to List</a>
{% endblock %}

timber_crops/crops_optimizer/templates/need_cat_list.html
{% extends "base.html" %}

{% block content %}
<h1>Need Categories</h1>
<a href="{% url 'need_cat_create' %}" class="btn btn-primary">Create New</a>
<br><br>
<table class="styled-table" style="width: 400px">
    <thead>
        <tr>
            <th>Actions</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        {% for category in need_cat %}
            <tr>
                <td style="display: flex; justify-content: space-around;">
                    <a href="{% url 'need_cat_update' category.pk %}" class="btn update-button">Update</a>
                    <form method="post" action="{% url 'need_cat_delete' category.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn delete-button">Delete</button>
                    </form>
                </td>
                <td>{{ category.name }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

timber_crops/crops_optimizer/templates/resource_cat_form.html
{% extends "base.html" %}

{% block content %}
<h1>{% if 'create' in request.path %}Create
    {% else %}Update{% endif %} 
    Resource Category</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
        {% if 'create' in request.path %}Create
        {% else %}Update{% endif %}</button>
</form>
<br><br>
<a href="{% url 'resource_cat_list' %}">Back to List</a>
{% endblock %}

timber_crops/crops_optimizer/templates/resource_form.html
{% extends "base.html" %}

{% block content %}
<h1>{% if 'create' in request.path %}Create
    {% else %}Update{% endif %} 
    Resource</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">
        {% if 'create' in request.path %}Create
        {% else %}Update{% endif %}</button>
</form>
<br><br>
<a href="{% url 'resource_list' %}">Back to List</a>
{% endblock %}